# Generated by Django 3.0.1 on 2020-01-14 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses_hub', '0002_application'),
        ('login_register_service_hub', '0002_customuser_lease'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='houses_hub.Application'),
        ),
    ]
