# Generated by Django 3.0.1 on 2020-01-22 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses_hub', '0003_auto_20200122_1232'),
        ('login_register_service_hub', '0005_auto_20200122_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='lease',
        ),
        migrations.AddField(
            model_name='customuser',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='houses_hub.Lease'),
        ),
    ]
