# Generated by Django 3.0.1 on 2020-01-24 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses_hub', '0005_application_submitted'),
        ('login_register_service_hub', '0006_auto_20200122_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='houses_hub.Lease'),
        ),
    ]
