# Generated by Django 3.0.7 on 2020-07-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses_hub', '0008_auto_20200606_1817'),
        ('login_register_service_hub', '0008_auto_20200517_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='lease',
        ),
        migrations.AddField(
            model_name='customuser',
            name='lease',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='houses_hub.Lease'),
        ),
    ]
