# Generated by Django 3.0.1 on 2020-01-22 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houses_hub', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='students',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses_hub.House'),
        ),
        migrations.CreateModel(
            name='ApplicationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_details', models.CharField(max_length=2000)),
                ('money', models.CharField(max_length=200)),
                ('letter_of_recommendation', models.CharField(max_length=2000)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='students_info',
            field=models.ManyToManyField(to='houses_hub.ApplicationInfo'),
        ),
    ]
