# Generated by Django 3.0.1 on 2020-01-23 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses_hub', '0003_auto_20200122_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='students_info',
        ),
        migrations.AddField(
            model_name='applicationinfo',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='houses_hub.Application'),
        ),
    ]
