# Generated by Django 3.0.7 on 2020-06-06 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses_hub', '0007_house_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=200)),
                ('city_or_town', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='number_of_bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='number_of_rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='HousePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses_hub.House')),
            ],
        ),
    ]
