# Generated by Django 3.0.6 on 2020-05-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
