# Generated by Django 3.0.7 on 2020-07-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='message',
            field=models.CharField(default='HELLO WORLD', max_length=500),
            preserve_default=False,
        ),
    ]
