# Generated by Django 3.0.7 on 2020-07-19 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatapp', '0002_chat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='student',
        ),
        migrations.AddField(
            model_name='chat',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatapp.Conversation'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='students',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
