# Generated by Django 3.0.7 on 2020-07-19 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_auto_20200719_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 10, 40, 52, 743695)),
        ),
        migrations.AddField(
            model_name='conversation',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 10, 40, 52, 743695)),
        ),
    ]
