# Generated by Django 3.0.7 on 2020-07-19 09:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_auto_20200719_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 9, 42, 9, 208359, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 9, 42, 9, 207362, tzinfo=utc)),
        ),
    ]
