# Generated by Django 3.0.7 on 2020-07-19 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_auto_20200719_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date_sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
